---
- name: "Installation on IP Host"
  hosts: Ubuntu_Hosts
  tasks:
  - name: Install Htop APT
    become: True
    become_user: root                                                                                                                      
    apt:
      update_cache: yes
      name: netcat
      state: latest
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  

#- name: "Download files to Host"
#  hosts: Ubuntu_Hosts
#  tasks:
#  - name:
#    fetch:
#      #remote_src: true
#      src: /home/ubuntu/destination/test_download.txt
#      dest: /Users/km/Documents/Ansible/vm/2.0
#      state: file



#- name: "Download files to Host"
#  hosts: Ubuntu_Hosts
#  tasks:
#  - name:
#    fetch:
#      #remote_src: true
#      src: /Users/km/Documents/Ansible/vm/2.0/nc.sh
#      dest: /home/ubuntu/destination/nc.sh
#      state: file




#- name: "sending and recieving Messages"
#  hosts: Ubuntu_Hosts  
#  tasks:
#  - name: send message from Ubuntu to Debian, command only on ubuntu                                                                                                                            #
#    command: cat test.txt | netcat 86.119.0. 23

 

#- name: "sending a messages"
#  hosts: Ubuntu_Hosts  
#  tasks:
#  - name: run nc.sh to send message
#    delegate_to: localhost                                                                                                                           #
#    shell: openstack server list    
    #become: True                                                                                                               #
    #when: ansible_distribution == 'Ubuntu'   
  
  #- name: recieve message, listening to port 23 on Debian                                                                                                                              #
  #  command: netcat -l -p 23  
  #  become: True                                                                                                                  #
  #  when: ansible_distribution == 'Debian'

